styled posts and removed unnecessary files
bmbaron/blog pull request #1
Opened 2023-10-15 17:13 UTC by bmbaron

2023-10-16 15:55 UTC, bmbaron commented
<img width="1381" alt="image" src="https://github.com/bmbaron/blog/assets/20213304/02ba7d59-a940-42d9-8f16-f6fc371bf44b">

Laptop

<img width="193" alt="image" src="https://github.com/bmbaron/blog/assets/20213304/07b79f6b-fee1-4e6e-aee2-06a3e9385ffc">

Mobile

2023-10-17 07:47 UTC, qkudev requested changes

2023-10-17 07:47 UTC, qkudev commented on public/index.html
> -    -->
Why did you deleted these lines?

Actually, I don't think you should do it. But really, what is the reason?

2023-10-17 07:47 UTC, qkudev commented on src/App.tsx
> +      {/*<button onClick={removeSecondPost}>remove 2nd post</button>*/}
Remove this comment, please

I does nothing

2023-10-17 07:47 UTC, qkudev commented on src/app.styled.ts
> +export const MainContainer = styled('div')`
Use `main`, please

It is a good practice for Search Engines and screen readers to use semantic HTML tags.

Take a look [here](https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantics_in_html)

And [there is](https://web.dev/learn/accessibility/) also a good accessibility course by Google developers

2023-10-17 07:47 UTC, qkudev commented on src/components/PostsList/postsLists.styled.ts
> +  margin: 20px auto;
I see you are using much hard coded spacings like margin and padding

It is a good practice to use `theme` from `styled-components`

Could you please add `xstyled`? Lets start with spacings and typography!

You can check out the docs [here](https://xstyled.dev/docs/magic-styled-components/)

2023-10-17 07:47 UTC, qkudev commented on src/components/Post/Post.tsx
>          <Title>{title}</Title>
Hey!

I think you could add `ui` directory with components that do not use any business logic and have only stylings and presentations.

Could you please create `ui/Title` directory and add common `Title` component?

2023-10-17 07:48 UTC, qkudev commented
Also it is a good practice to add description to your pull request with content like:

```
// markdown
# Changes

- adds `Post` and `PostList` components
- adds mocked posts data
```

2023-10-17 07:49 UTC, qkudev commented
Let me know when you add `xstyled` and then we will continue with `react-router` and app pages!

2023-10-23 11:12 UTC, bmbaron commented on public/index.html
> -    -->
Adding back in. I think I was a bit too "trigger happy" when trying to remove the boilerplate code.

2023-10-24 09:49 UTC, closed without merging